### ISSUE TITLE
lein-garden auto produces stale output

### ISSUE THREAD

**Issue by ghost** [noprompt/lein-garden#14]
Hi, I wanted to report an issue when using lein-garden's auto-mode with style definitions across multiple files.

It appears that auto-mode is not refreshing namespaces, so although lein-garden correctly notices changes in the source files, the changes never make it into the output file because their respective namespaces are not updated.

Here's a more concrete example of the problem:

-- Inside style.clj -- 

```
(ns app.style
  (:require [garden.def :refer [defstyles]]
            [app.style.menu :as menu]))

(defstyles style
  [menu/style])
```

-- Inside menu.clj --

```
(ns app.style.menu
  (:require [garden.def :refer [defstyle]]))

(defstyles style
  [:body {:background "red"}])
```

-- Leiningen project definition --

```
:garden {:builds [{:stylesheet app.style/style
                   :compiler {:output-to "resources/output.css"
                              :pretty-print? false}}]}
```

When making a change to menu.clj (for example changing the background color from "red" to "blue"), lein-garden will notice the change and recompile the output, however the contents will be unchanged, the background color will remain "red".

I haven’t had time to look into this deeply, but it seems like the load-namespaces function (line 37) is only updating the namespace listed in the Leiningen project file and not all of the namespaces it depends on. Does anyone know how to update this?

Garden is so awesome!

**Comment by fl00r** [comment]
I have met the same problem. Haven't figured out the reason though.

**Comment by fl00r** [comment]
The problem was in ns-tracker library.
You use 0.3.0, while if there is a newer version (0.3.1) it will lead to wrong behavior.

In 0.3.0 when you make a change in some ns it will return all namespaces from the root one to the changed one and 0.3.1 will return only changed ns and it reloading this namespace won't lead to reloading of the main var with your stylesheet.

Workround is to use explicitly `[ns-tracker "0.3.0"]` in your dependencies in project.clj
