### ISSUE TITLE
Can't use pseudo classes with double colons?

### ISSUE THREAD

**Issue by zentrope** [noprompt/lein-garden#34]
Wanted to do this:

```clojure
[:button {}
  [:&::-moz-focus-inner {:border 0}]]
```

but got an error:

```clojure
Error: java.lang.RuntimeException: Invalid token: :&::-moz-focus-inner
```

I was able to work around it with:

```clojure
[:button {}
  [(keyword "&::-moz-focus-inner") {:border 0}]]
```

Bug? Works as designed? I don't know, but there it is. ;)

**Comment by noprompt** [comment]
This is not an issue for this project, however, the error should be an indicator that the problem is not with Garden; it's with the Clojure. Though you can create a keyword as you have done from the string you cannot enter that literally into a file or the REPL. FWIW there's no reason you need to use a keyword for that selector. A string will work just as well.
